name: list_mate
description: Create lists easily - Flutter Create 2019 entrant.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: "^0.3.0"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/d.json
   - assets/coffee.png

  fonts:
   - family: Montserrat
     fonts:
       - asset: fonts/Montserrat-Regular.otf
         weight: 400
       - asset: fonts/Montserrat-Bold.otf
         weight: 700
